application: paleo-search
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: media/img/favicon.ico
  upload: media/img/favicon.ico
- url: /webResrouces.csv
  static_files: static/webResrouces.csv
  upload: static/webResrouces.csv
- url: /webResrouces.n3
  static_files: static/webResrouces.n3
  upload: static/webResrouces.n3
- url: /c4pSKOS.n3
  static_files: static/c4pSKOS.n3
  upload: static/c4pSKOS.n3
- url: /annotations.xml
  static_files: static/annotations.xml
  upload: static/annotations.xml
- url: /opensearch.xml
  static_files: static/opensearch.xml
  upload: static/opensearch.xml
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt 
- url: /data
  static_files: static/data.html
  upload: static/data.html
- url: /
  script: _go_app
- url: /sandbox
  script: _go_app
- url: /static
  static_dir: static
